routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get( '/', function () {
	return view( 'welcome' );
} );

Auth::routes();

Route::get( '/home', 'HomeController@index' )->name( 'home' );

Route::get( '/tasks/{id}/change-status', 'TasksController@changeStatus' )
	 ->name( 'task.change-status' );
Route::resource( 'tasks', 'TasksController' );
Route::resource( 'users', 'UsersController' );
Route::get( 'uncompleted', 'TasksController@uncompleted' );

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function tasks() {
        return $this->hasMany(Task::class);
    }

    public function completed_tasks() {
		return $this->hasMany(Task::class, 'user_id', 'id')
					->where('status', '=', 1);
	}

	public function pending_tasks() {
		return $this->hasMany(Task::class, 'user_id', 'id')
					->where('status', '=', 2);
	}
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Task;
use App\User;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        
        return view('users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

		$user = User::find($id);

		return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
      
       
        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(User $user)
    {
        $user->update($this->validateRequest());

        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();
        return redirect()->route('users.index');
    }

    private function validateRequest() {
        return request()->validate([
            'name' => 'required|min:3',
            'email' => 'required|email',
            
        ]);
    }
}

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1>Redaguoti duomenis: {{ $user->name }}</h1>
        </div>
        <div class="col-sm-12">
            <form method="POST" action="{{ route('users.update', $user->id) }}">
                @csrf
                @method('PUT')

                <div class="form-group">
                    <label>Name</label>
                    <input type="text" name="name" value="{{ $user->name }}" class="form-control" />
                </div>

                <div class="form-group">
                    <label>E-mail</label>
                    <input type="text" name="email" value="{{ $user->email }}" class=" form-control" />
                </div>

                


                <div class="form-group">
                    <input type="submit" class="btn btn-success" value="Redaguoti" />
                </div>

            </form>
        </div>
    </div>
</div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('title', 'Vartotojai')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-12">

            <h1>Users' List</h1>

        </div>
    </div>
</div>
<div class="container">
    @foreach($users as $user)
    <div class="row">
        <div class="col-2">
            <a href="{{ route('users.show',$user->id) }}">{{ $user->name}} </a>
        </div>
        <div class="col-2">
            <form action="{{ route('users.destroy',$user->id) }}" method="POST">
                @csrf
                @method('DELETE')

                <button type="submit" class="btn btn-danger">Ištrinti</button>
            </form>
        </div>
        <div class="col-2">
            <a class="btn btn-primary" href="{{ route('users.edit',$user->id) }}">Redaguoti</a>
        </div>


    </div>
    @endforeach
</div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')


@section('content')

<div class="container">

    <div class="row">
        <div class="col-12">
            <h1>{{ $user->name }}</h1>

            <div>
                Atliktos uzduotys: {{ $user->completed_tasks->count() }}
            </div>

            <div>
                Neatliktos uzduotys: {{ $user->pending_tasks->count() }}
            </div>
            <hr>

            <h3>Uzduotys</h3>

            <ul>
                @foreach($user->tasks as $task)
                    <li>{{ $task->name }}</li>
                @endforeach
            </ul>

        </div>
    </div>
</div>
@endsection