routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get( '/', function () {
	return view( 'welcome' );
} );

Auth::routes();

Route::get( '/home', 'HomeController@index' )->name( 'home' );

Route::get( '/tasks/{id}/change-status', 'TasksController@changeStatus' )
	 ->name( 'task.change-status' );
Route::resource( 'tasks', 'TasksController' );
Route::resource( 'users', 'UsersController' );
Route::get( 'uncompleted', 'TasksController@uncompleted' );

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $table = "tasks";

    protected $guarded = [];


    // pridedame laukelius
	protected $dates = ['deadline'];


	protected $attributes = [
        'status' => 2
    ];

    public function getStatusAttribute($attribute)
    {
        return $this->statusOptions()[$attribute];
    }

    public function user() {
        return $this->belongsTo(User::class);
    }

    public static function uncompleted() {
    	return Task::where('status', '=', 0)->get();
	}

    public function scopePending($query)
    {
        return $query->where('status', 2);
    }

    public function scopeCompleted($query)
    {
        return $query->where('status', 1);
    }

    public function scopeUncompleted($query)
    {
        return $query->where('status', 0);
    }

    public function statusOptions()
    {
        return [
            2 => 'Pending',
            1 => 'Completed',
            0 => 'Uncompleted',
        ];
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Task;
use App\User;

class TasksController extends Controller
{

    public function __construct() {

        
        $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::all();
        
        return view('tasks.index', compact('tasks'));
    }

    public function uncompleted()
    {
        $uncompletedTasks = Task::uncompleted();
        $users = User::all();
        
        return view('tasks.uncompleted', compact('uncompletedTasks', 'tasks'));
    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all();
        $task = new Task();

        return view('tasks.create', compact('users', 'task'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Task::create($this->validateRequest());
       
        return redirect()->route('tasks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $task = Task::findOrFail($id);
        return view('tasks.show', compact('task'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $task = Task::findOrFail($id);
        $users = User::all();
		return view('tasks.edit', compact('task', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $task = Task::findOrFail($id);
        $task->update($this->validateRequest());

        return redirect()->route('tasks.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::findOrFail($id);
        $task->delete();
        return redirect()->route('tasks.index');
    }


    private function validateRequest() {
        return request()->validate([
            'name' => 'required|min:3',
            'description' => 'required|max:255',
            'user_id' => 'required',
            'deadline' => 'required',
            'status' => 'required',
            
        ]);
    }


    public function changeStatus($id) {
		$tasks = Task::find($id);

		if($tasks->status == 'Completed') {
			$tasks->status = 0;
		} else if($tasks->status == 'Pending' || $tasks->status == 'Uncompleted') {
			$tasks->status = 1;
		}

		$tasks->save();

		return redirect()->back();
	}




}

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('title', 'Naujos užduoties sukūrimas')

@section('content')

<div class="container">

    <div class="col-12">
        <form  method="POST" action="{{ route('tasks.store') }}">


            @include('tasks.form')

            <button type="submit" class="btn btn-primary">Add Customer</button>
        </form>
    </div>
</div>


<script>
    CKEDITOR.replace('description');
</script>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('title', 'Redaguoti: ' . $task->name . 'užduotį')

@section('content')

<div class="row">
    <div class="col-12">

        <h1> užduoties: {{ $task->name }} redagavimas </h1>
    </div>
</div>

<div class="row">
    <div class="col-12">

        <form method="POST" action="{{ route('tasks.update', $task->id) }}">
            @method('PATCH')
            @include('tasks.form')

            <button type="submit" class="btn btn-primary">Save Task</button>
        </form>
    </div>
</div>

<script>
    CKEDITOR.replace('description');
</script>

@endsection

resources/views/tasks/form.blade.php
<div class="form-group">
    <label for="name">Name:</label>
    <input class="form-control" type="text" name="name" value="{{ old('name') ?? $task->name }}">
</div>


<div class="form-group">
    <label for="description">Description:</label>
    <textarea name="description" id="description" class="form-control">{{ old('description') ?? $task->description }}</textarea>
</div>

<div class="form-group">
<label for="user">Kam priskirta užduotis:</label>
    <select class="form-control" name="user_id">
        @foreach($users as $user)
        <option value="{{ $user->id }}">
            {{ $user->name }}
        </option>
        @endforeach
    </select>
</div>

<div class="form-group">
    <label>Data iki kuriuos reikia užbaigti užduotį:</label>
    <input type="date" name="deadline" value="{{ old('deadline') ?? $task->deadline }}" class="form-control" />
</div>

<div class="form-group">
    <label for="status">Užduoties statusas:</label>
    <select name="status" id="status" class="form-control">
        <option value="" disabled>Užduoties būsena</option>
        @foreach($task->statusOptions() as $statusOptionKey => $statusOptionValue)
            <option value="{{ $statusOptionKey }}" {{ $task->status == $statusOptionValue ? 'selected' : '' }}>{{ $statusOptionValue }}</option>
        @endforeach
    </select>
</div>


@csrf

resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('title', 'Užduotys')

@section('content')
<div class="row">
    <div class="col-12">

        <h1>Tasks' List</h1>
        <a class="btn btn-success" href="{{ route('tasks.create') }}">Pridėti naują uzduoti</a>
    </div>
</div>

@foreach($tasks as $task)
<div class="row">
    <div class="col-2">
    <a href="{{ route('tasks.show',$task->id) }}">{{ $task->name}} </a>
    </div>
    <div class="col-4">
        {{ $task->user->name}}
    </div>
    <div class="col-4">
        {{ $task->deadline->format('Y-m-d') }}
    </div>
    <div class="col-2">
        {{ $task->status }}
    </div>

</div>
@endforeach

@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')

@section('title', 'Uzduotis: ' . $task->name)

@section('content')

    <div class="row">
        <div class="col-12">
            <h1>Uzduotis: {{ $task->name}}</h1>
            <p><a class="btn btn-primary" href="{{ route('tasks.edit',$task->id) }}">Redaguoti</a></p>
            <form action="{{ route('tasks.destroy',$task->id) }}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">Ištrinti</button>
            </form>

            @if($task->status == 'Completed')
                <a href="{{ route('task.change-status', $task->id) }}" class="btn btn-success mt-3">
                    Pazymeti kaip neatlikta
                </a>
            @else
                <a href="{{ route('task.change-status', $task->id) }}" class="btn btn-success mt-3">
                    Pazymeti kaip atlikta
                </a>
            @endif


        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-12">
            <p><strong>Name</strong> {{ $task->name }}</p>
            <p><strong>Status</strong> {{ $task->status }}</p>
            <p><strong>Company</strong> {{ $task->user->name }}</p>

        </div>
    </div>
@endsection

resources/views/tasks/uncompleted.blade.php
@extends('layouts.app')

@section('title', 'Užduotys')

@section('content')
<div class="row">
    <div class="col-12">

        <h1>Uncompleted Tasks' List</h1>
        <ul>
            @foreach($uncompletedTasks as $uncompletedTask)
            <li><a href="{{ route('tasks.show',$uncompletedTask->id) }}">{{ $uncompletedTask->name}} </a></li>

            @endforeach
        </ul>
    </div>
</div>
@endsection